source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FDStackView_Example', :exclusive => true do
  pod "FDStackView", :path => "../"
end

target 'FDStackView_Tests', :exclusive => true do
  pod "FDStackView", :path => "../"

  
end
